### ISSUE TITLE
windef.h include via windows.h include causes issue with "near" and "far" names

### ISSUE THREAD

**Issue by nvibd** [NVIDIA/libcudacxx#130]
In our application related to 3D geometry, we use `near` and `far` names. Recently, we started using libcu++ and more specifically `<cuda/std/atomic>`. However, this causes issues as there is an indirect inclusion of "windef.h", which `#define`s "near" and "far" to nothing. 

There are some possible workarounds, including adding `#undef`s for "near" and "far" after every libcu++ include, or renaming all conflicting variables. 

Still, it would be preferable if libcu++ would somehow avoid or prevent these extra macro definitions coming from "windows.h".

**Comment by nvibd** [comment]
Here's a minimal example that causes compilation errors. Save as `.cu` or `.cpp` file, compile with `nvcc.exe` or `cl.exe` with the libcu++ includes.

```
#include <cuda/std/atomic>

struct A {
  float near;
  float far;
};

int main() { }
```

**Comment by nvibd** [comment]
cl.exe version:
`Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29336 for x64`
nvcc.exe version:
`Cuda compilation tools, release 11.2, V11.2.67`

**Comment by miscco** [comment]
Unfortunately there is nothing we can do here.

**Comment by nvibd** [comment]
Would `#undef`s for `near` and `far` after "windef.h" includes inside libcu++ not be a workable fix?

**Comment by miscco** [comment]
We cannot #undef macros from a system header. 

While at the moment the macro might be useless it could get some meaning in the future leading to havoc
