### ISSUE TITLE
Document extension: we guarantee cuda::barrier constructor is trivially constructible

### ISSUE THREAD

**Issue by gonzalobg** [NVIDIA/libcudacxx#138]
We guarantee that `cuda::barrier` has a trivial constructor, this is required for the `pipeline_shared_state` to be trivially constructible. We should document this.

From this it follows that the constructor of the pipeline shared state is also trivial, should probably document this as well.

**Comment by ogiroux** [comment]
We should also say that it's constexpr constructible now, which allows you to put one in `__managed__` and `__device__` memory.

**Comment by gonzalobg** [comment]
Closing because I don't think we have to say anything here. 

`std::barrier` doesn't declare a default constructor, and neither does libcudacxx. Therefore, the default constructor is implicitly defined, and if this constructor can be constexpr, then the standard guarantees that this is the case.

**Comment by gonzalobg** [comment]
cc @griwes to double check the above
