### ISSUE TITLE
libcu++ atomic fails to compile with address sanitizer (ASAN) enabled

### ISSUE THREAD

**Issue by maddyscientist** [NVIDIA/libcudacxx#142]
In testing libcu++ for deployment in QUDA, I found that libcu++ atomic fails to compile if address sanitizer is enabled.
```bash
$ nvcc bug.cu -o bug -arch=sm_70 -Xcompiler -fsanitize=address -Ilibcudacxx/include
libcudacxx/include/cuda/std/detail/libcxx/include/__config(1466): error: attributes are not allowed here

1 error detected in the compilation of "bug.cu".
```
Where bug.cu is simply the following
```c++
#include <cuda/atomic>
int main() { }
```
I note that this is blocking us from deploying libcu++ for production in QUDA, and forcing us to keep around legacy our legacy `atomicAdd`-based and `cudaStream` approach to reductions.

Tested on the latest release 1.4.1.

**Comment by brycelelbach** [comment]
@griwes thoughts

**Comment by ogiroux** [comment]
I took a quick look. There's a very special function at this line of code, some kind of compact between libcxx and ASAN, and it has one of the macros we modified applied to it. I bet that if we just unapplied our modified macro from it (after all, it's not a GPU function) then it would either pass or find the next error.

**Comment by miscco** [comment]
This has been fixed by https://github.com/NVIDIA/libcudacxx/pull/206 AFAIK so closing
