### ISSUE TITLE
Support half/bf16 For Complex

### ISSUE THREAD

**Issue by cliffburdick** [NVIDIA/libcudacxx#153]
Currently there are no specializations for `__half` or `__nv_bfloat16` types. It would be useful for writing generic code using the complex libraries if these could be supported as first-class types.

**Comment by leofang** [comment]
The `__half` part is a duplicate of https://github.com/NVIDIA/libcudacxx/issues/95 🙂

**Comment by cliffburdick** [comment]
Closing as dupe
