### ISSUE TITLE
Add `cuda::std::optional`

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/libcudacxx#169]
Since we're doing `std::variant` (#162), we probably ought to do `std::optional` as well.

**Comment by ericniebler** [comment]
@griwes are you working on a `cuda::optional`? Can I assign this to you?

**Comment by mhoemmen** [comment]
I'm interested in both `optional` and `variant`.

**Comment by w3ntao** [comment]
Does it work now?
