### ISSUE TITLE
Do we have specific hardware requirements to build the library?

### ISSUE THREAD

**Issue by 77Bala7790** [NVIDIA/libcudacxx#174]
I am getting the below error when trying to test the library in my digital ocean Linux box. (It doesn't have GPUs in it)

Command: **root@recon:~/libcudacxx/build# ../utils/nvidia/linux/perform_tests.bash --skip-libcxx-tests**
\
################################################################################
# TEST SM Architecture Detection
lit: /root/libcudacxx/utils/libcxx/test/config.py:40: note: using site specific configuration at /root/libcudacxx/build/libcxx/test/lit.site.cfg
lit: /root/libcudacxx/test/lit.cfg:45: note: Using configuration variant: libcxx
lit: /root/libcudacxx/utils/libcxx/test/config.py:360: note: inferred use_system_cxx_lib as: None
lit: /root/libcudacxx/utils/libcxx/test/config.py:245: note: detected cxx.type as: nvcc
lit: /root/libcudacxx/utils/libcxx/test/config.py:247: note: detected cxx.version as: ('10', '1', '243')
lit: /root/libcudacxx/utils/libcxx/test/config.py:249: note: detected cxx.default_dialect as: c++14
lit: /root/libcudacxx/utils/libcxx/test/config.py:251: note: detected cxx.is_nvrtc as: False
lit: /root/libcudacxx/utils/libcxx/test/config.py:279: note: detected host_cxx.type as: gcc
lit: /root/libcudacxx/utils/libcxx/test/config.py:281: note: detected host_cxx.version as: ('9', '3', '0')
lit: /root/libcudacxx/utils/libcxx/test/config.py:283: note: detected host_cxx.default_dialect as: c++14
lit: /root/libcudacxx/utils/libcxx/test/config.py:285: note: detected host_cxx.is_nvrtc as: False
lit: /root/libcudacxx/utils/libcxx/test/config.py:387: note: inferred use_clang_verify as: False
lit: /root/libcudacxx/utils/libcxx/test/target_info.py:67: warning: The locale fr_FR.UTF-8 is not supported by your platform. Some tests will be unsupported.
lit: /root/libcudacxx/utils/libcxx/test/target_info.py:67: warning: The locale ru_RU.UTF-8 is not supported by your platform. Some tests will be unsupported.
lit: /root/libcudacxx/utils/libcxx/test/target_info.py:67: warning: The locale zh_CN.UTF-8 is not supported by your platform. Some tests will be unsupported.
lit: /root/libcudacxx/utils/libcxx/test/target_info.py:67: warning: The locale fr_CA.ISO8859-1 is not supported by your platform. Some tests will be unsupported.
lit: /root/libcudacxx/utils/libcxx/test/target_info.py:67: warning: The locale cs_CZ.ISO8859-2 is not supported by your platform. Some tests will be unsupported.
lit: /root/libcudacxx/utils/libcxx/test/config.py:480: note: inferred long_tests as: True
lit: /root/libcudacxx/utils/libcxx/test/config.py:315: fatal: Command: ['/usr/bin/nvcc', '-x', 'cu', '/dev/null', '-E', '-v', '-ftemplate-depth=270', '-ccbin=g++', '-std=c++11', '-include', '/root/libcudacxx/test/support/nasty_macros.h', '-I/root/libcudacxx/include', '-I/root/libcudacxx/build/libcxx/include/c++build', '-D__STDC_FORMAT_MACROS', '-D__STDC_LIMIT_MACROS', '-D__STDC_CONSTANT_MACROS', '-Xcompiler', '-fno-exceptions', '-Xcompiler', '-fno-rtti', '-D_LIBCUDACXX_NO_RTTI', '-I/root/libcudacxx/test/support', '-include', '/root/libcudacxx/test/force_include.h', '-I/root/libcudacxx/include', '-I/root/libcudacxx/../cuda/tools/cooperative_groups', '-I/root/libcudacxx/../cuda/tools/libcudacxxext', '--extended-lambda', '-gencode=arch=compute_35,code=sm_35', '-gencode=arch=compute_50,code=sm_50', '-gencode=arch=compute_52,code=sm_52', '-gencode=arch=compute_53,code=sm_53', '-gencode=arch=compute_60,code=sm_60', '-gencode=arch=compute_61,code=sm_61', '-gencode=arch=compute_62,code=sm_62', '-gencode=arch=compute_70,code=sm_70', '-gencode=arch=compute_72,code=sm_72', '-gencode=arch=compute_75,code=sm_75', '-gencode=arch=compute_80,code=sm_80', '-gencode=arch=compute_80,code=compute_80', '-Xcudafe', '--display_error_number', '-Werror', 'all-warnings', '-Xcompiler', '-Wall', '-Xcompiler', '-Wextra', '-Xcompiler', '-Werror', '-Xcompiler', '-Wno-literal-suffix', '-Xcompiler', '-Wno-unused-parameter', '-Xcompiler', '-Wno-deprecated-declarations', '-Xcompiler', '-Wno-noexcept-type', '-Xcompiler', '-Wno-unused-function', '-D_LIBCUDACXX_DISABLE_PRAGMA_GCC_SYSTEM_HEADER', '-Xcompiler', '-dM']
Exit Code: 1
Standard Error:
--
nvcc fatal   : Unknown option '-extended-lambda'
--

Compiler failed unexpectedly when dumping macros!
################################################################################
Score: 0.00%

**Comment by wmaxey** [comment]
It seems that our tests are using `--extended-lambda`. That option is not supported likely on CUDA 10.1.

It might be worthwhile checking out an older tag of libcudacxx as it may not have that requirement.

I don't believe we have any validation for toolkits as old as 10.1. This would be an opportunity for feedback if you encounter issues when using the library regardless of test compatibility.

**Comment by wmaxey** [comment]
Closing as this isn't an actionable issue.
