### ISSUE TITLE
cmake .. throws that it can't find libatomic.

### ISSUE THREAD

**Issue by bala-thenightskycoder** [NVIDIA/libcudacxx#175]
CMake Warning at libcxx/cmake/Modules/CheckLibcxxAtomic.cmake:54 (message):
  Host compiler appears to require libatomic, but cannot find it.
Call Stack (most recent call first):
  libcxx/cmake/config-ix.cmake:76 (include)
  libcxx/CMakeLists.txt:488 (include)

-- Linker detection: unknown
-- there is no pre-generated ABI list for the requested libc++ configuration. check-cxx-abilist target is not supported
-- Configuring done
-- Generating done
-- Build files have been written to: /root/libcudacxx/build

Is the above thing means it had build correctly? In Linux environment.

**Comment by wmaxey** [comment]
That's fine, this would be an expected failure. :)

We don't (yet) have any source file components so the build files created are primarily just configuration files for lit to use when testing.

**Comment by jrhemstad** [comment]
Based on https://stackoverflow.com/a/64112384, this check appears to be buggy anyways. 

We can work around it by manually specifying:
```
set(HAVE_CXX_ATOMICS64_WITHOUT_LIB True)
set(HAVE_CXX_ATOMICS_WITHOUT_LIB True)
```
