### ISSUE TITLE
Redistributable

### ISSUE THREAD

**Issue by seanbaxter** [NVIDIA/libcudacxx#214]
I'm interested in supporting this library on my own compiler. Do you provide a binary redistributable that covers the non-header portions of the library? Would that be hiding in the hpc toolkit somewhere? Basically I'm looking for guidance on deployment.

**Comment by brycelelbach** [comment]
It's header only - there's no binary component.

**Comment by wmaxey** [comment]
You are correct, those are functional underpinnings of our library. However, we do not expose those to users.

The only front-end that should be available to users are the files located in `include/cuda/std` anything below that directory is outside of the scope of what libcudacxx supports.

Yes, someone could forcefully include `include/cuda/std/detail/libcxx/include/iostream`, but that would quickly fail for a variety of reasons. (e.g. https://stackoverflow.com/questions/68075342/how-do-i-properly-include-files-from-the-nvidia-c-standard-library)

Libcudacxx is an extremely slim implementation of some memory model fundamentals, synchronization, and a growing subset of utilities. Things like memory allocation and iostream are on the roadmap, but will require more design and time. :(

**Comment by seanbaxter** [comment]
I'm not expecting to use any of that stuff on the device. My understanding is that this is a fork of libc++ with some special sauce for GPU, but that it works for the whole system. How do I use iostreams, etc, on the host? I wouldn't be simultaneously including both libcudacxx and libstdc++, rigth?

**Comment by griwes** [comment]
Your understanding is incorrect. At this time, libcu++ does not implement `namespace std`, but implements versions of a partial subset of it as `cuda::std`, and extentions to some of these (plus some additional APIs) in `namespace cuda`.

Please refer to the documentation to see what is supported at this time.
