### ISSUE TITLE
[BUG] atomic is not trivially copyable when used inside template class

### ISSUE THREAD

**Issue by karthikeyann** [NVIDIA/libcudacxx#218]
With libcudacxx 1.6.0, `nvcc -std=c++17 atomic_test.cu -arch=sm_70`, following code causes
```
atomic_test.cu(7): error C2338: device_uvector only supports types that are trivially copyable.
atomic_test.cu(24): note: see reference to class template instantiation 'rmm::device_uvector<cuda::__4::atomic<scan_tile_status,cuda::std::__4::__detail::thread_scope_device>>' being compiled
```

```cpp
#include <cuda/atomic>
namespace rmm {
template <typename T>
class device_uvector {
  static_assert(std::is_trivially_copyable<T>::value, //Line 7
                "device_uvector only supports types that are trivially copyable.");
  public:
  device_uvector(size_t i) {}
};
}
enum class scan_tile_status : uint8_t {
  oob,
  invalid,
  partial,
  inclusive,
};

using type_t = cuda::atomic<scan_tile_status, cuda::thread_scope_device>;
int main() {
  static_assert(std::is_trivially_copyable<type_t>::value, "type is not trivially copyable."); //Line 22

  rmm::device_uvector<type_t> tile_status(10); // Line 24
}
```

static_assert in line 22 passed. But static_assert in line 7 failed!
Both are same types, only difference is the template type.
Same code compiles in Linux.

<details>
<summary>Details</summary>
Windows 10

used libcudacxx 1.6.0

`nvcc -std=c++17 atomic_test.cu -arch=sm_70 -I C:\Users\user\Documents\cudf\libcudacxx-1.6.0\include`

nvcc --version
Built on Sun_Feb_14_22:08:44_Pacific_Standard_Time_2021
Cuda compilation tools, release 11.2, V11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0

</details>

**Comment by miscco** [comment]
@wmaxey @griwes Given that the original bug has been fixed I believe we should close this
