### ISSUE TITLE
Rename deprecated `diag_suppress` to `nv_diag_suppress` for CTK11.5 build

### ISSUE THREAD

**Issue by cjnolet** [NVIDIA/libcudacxx#226]
I am getting the following while testing CTK 11.5 to test building RAPIDS RAFT and cuML:

`/share/workspace/rapids_projects/raft/cpp/build/_deps/libcudacxx-src/include/cuda/std/detail/../chrono(34): error #20236-D: pragma "diag_suppress" is deprecated, use "nv_diag_suppress" instead`

I believe this could be throwing an error instead of warning because of a flag we've enabled in the build, but ideally we would not encounter these warnings at all.

**Comment by wmaxey** [comment]
Thanks! Can you let me know what version of libcudacxx you are using?

Older versions will leak this warning.

**Comment by wmaxey** [comment]
Closing as there has not been an update in some time.
