### ISSUE TITLE
Not compatible with g++ host compiler

### ISSUE THREAD

**Issue by drnikolaev** [NVIDIA/libcudacxx#229]
Tested on Ubuntu 20.04 (g++ 9), the following fails to compile:
`~/.../libcudacxx$ CPLUS_INCLUDE_PATH=include:libcxx/fuzzing:libcxx/include g++ -std=c++17 libcxx/test/libcxx/fuzzing/nth_element.cpp libcxx/fuzzing/fuzzing.cpp 
`
Just clone v1.7.0-ea, cd to libcudacxx and run the command pasted above.
This is the most minimalist sample I could find but the problem is wide spreaded, all attempts to integrate libcudacxx with g++ projects fail to compile like that.

**Comment by cliffburdick** [comment]
This happens on g++9.3 by just including cuda/std/cmath in an empty file.

**Comment by wmaxey** [comment]
Addressed in #234.
