### ISSUE TITLE
[RFE] std::experimental::fixed_size_simd and arithmetic operators

### ISSUE THREAD

**Issue by kerrmudgeon** [NVIDIA/libcudacxx#235]
This requests `std::experimental::fixed_size_simd` and arithmetic operators to be added to libcu++.

This would result in a unified, portable exposure of operations that are accelerated by vector operations in NVIDIA GPU hardware, including:
- elementwise multiply
- elementwise add
- elementwise multiply-add (e.g. half <= half * half + half, bfloat16 <= bfloat16 * bfloat16 + bfloat16).
- convert-and-pack (int8 <= float, half <= float, bfloat16 <= float)
- transcendental functions available in the CUDA Math Library (e.g. sqrt, exp, tanh, log, log10, erf, sin, cos, tan)

CUTLASS currently implements the above as [partial specializations of <functional> operators](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/functional.h) and extensions. This is non-standard. CUTLASS would drop its implementation and use libcu++'s implementation when it becomes available.

**Comment by miscco** [comment]
We are currently exploring implementing simd.

That said, there were considerable changes to the proposal in the last WG21 meeting so we are awaiting some of the changes from that

**Comment by jrhemstad** [comment]
Closing in favor of https://github.com/NVIDIA/cccl/issues/30
