### ISSUE TITLE
how to  support GPUDirect Storage in the new storage system？

### ISSUE THREAD

**Issue by zhenshuitieniu** [NVIDIA/libcudacxx#263]
hello，If I want to support GPUDirect Storage in the new storage system, in addition to the support of nvidia-fs.ko and new-fs-client.ko, do I need to do related adaptations in the cuda library?

It means that when nvidia-fs.ko supports the new file system, and the new-fs-client.ko also supports RDMA and GDS-related API calls, does it need to be supported at the cuda library level?

// These are same key values as the one's in the user space.
// When adding a new driver make sure to use the same values in user and kernel space.
#define NVFS_PROC_MOD_NVME_KEY "nvme"
#define NVFS_PROC_MOD_DDN_LUSTRE_KEY "lnet"
#define NVFS_PROC_MOD_GPFS_KEY "mmfslinux"
#define NVFS_PROC_MOD_NFS_KEY "rpcrdma"

**Comment by wmaxey** [comment]
I believe you're looking for the developer forums. This project is unrelated to GPUDirect.

https://forums.developer.nvidia.com/

**Comment by zhenshuitieniu** [comment]
thanks
