### ISSUE TITLE
`cuda::atomic_ref<float>::fetch_min` and `fetch_max` incorrect results on values of different signs

### ISSUE THREAD

**Issue by harrism** [NVIDIA/libcudacxx#279]
It looks like `cuda::atomic_ref<T>::fetch_min` for floating point types of `T` is not generating correct code. For these types a CAS loop implementation should be used, but as this Godbolt PTX shows, an unsigned integer `atom.max` is being generated. https://godbolt.org/z/sWeezx1a1

The problem is in the conversion to unsigned: negative and positive floats reinterpreted as unsigned integers will not compare in the same order. 

The code in the Godbolt does a max of positive values with the initial max set to a negative value. It also does a min of negative values with the initial min set to a positive value. Both result in incorrect results.

The correct output of the program should be 

```
0: Min: 0 Max: 511
1: Min: 512 Max: 1023
2: Min: 1024 Max: 1535
3: Min: 1536 Max: 2047
4: Min: 2048 Max: 2559
5: Min: 2560 Max: 3071
6: Min: 3072 Max: 3583
7: Min: 3584 Max: 4095
```

Instead, the program prints 

```
0: Min: 3.40282e+38 Max: -1
1: Min: 3.40282e+38 Max: -1
2: Min: 3.40282e+38 Max: -1
3: Min: 3.40282e+38 Max: -1
4: Min: 3.40282e+38 Max: -1
5: Min: 3.40282e+38 Max: -1
6: Min: 3.40282e+38 Max: -1
7: Min: 3.40282e+38 Max: -1
```

Tested on CUDA 11.5 on a Tesla V100 (DGX system).

Discovered when trying to convert cuSpatial to use libcudacxx `atomic_ref` rather than a custom implementation which uses atomicCAS.  RAPIDS would like to eliminate its custom atomic operation implementations, but this bug needs to be fixed first.

CC @jrhemstad

**Comment by wmaxey** [comment]
That's a solid bug. Thanks for the report. `atomic_ref` is really only rated to be used with integral types until we add PTX and special case handling for fp.

**Comment by harrism** [comment]
Should we not be using this feature then? If not, then please disable it. :)

**Comment by wmaxey** [comment]
Technically, it wasn't supposed to inherit from the atomic base classes that provide arithmetic support. This was certainly an issue in testing.

**Comment by ttnghia** [comment]
I also got incorrect with negative values:
 * Fill an int array with `std::numeric_limits<size_type>::min()`
 * Feed a sequence of `[0, 1, 2, ...]` into a function that:
 ```
auto const atomic_idx =
      cuda::atomic_ref<size_type, cuda::thread_scope::thread_scope_device>{d_output[idx]};
atomic_idx.fetch_max(idx, cuda::std::memory_order_relaxed);
```
And the result is `[-2147483648,-2147483648,......]`.

**Comment by ttnghia** [comment]
Here is the complete code to reproduce:
```

#include <cuda/std/atomic>

#include <thrust/device_vector.h>
#include <thrust/for_each.h>
#include <thrust/iterator/counting_iterator.h>
#include <thrust/uninitialized_fill.h>

#include <climits>
#include <iostream>
#include <vector>

//#define FIND_MIN
constexpr int SIZE{10};

void print(thrust::device_vector<int> const &v) {
  for (size_t i = 0; i < v.size(); ++i) {
    std::cout << v[i] << ",";
  }
  std::cout << "\n";
}

int main() {
  thrust::device_vector<int> d_v(SIZE);
#ifdef FIND_MIN
  thrust::uninitialized_fill_n(d_v.begin(), SIZE,
                               std::numeric_limits<int>::max());
#else
  thrust::uninitialized_fill_n(d_v.begin(), SIZE,
                               std::numeric_limits<int>::min());
#endif

  thrust::for_each_n(
      thrust::make_counting_iterator(0), SIZE,
      [d_v = thrust::raw_pointer_cast(d_v.data())] __device__(auto idx) {
        auto const atomic_idx =
            cuda::atomic_ref<int, cuda::thread_scope::thread_scope_device>{
                d_v[idx]};
#ifdef FIND_MIN
        atomic_idx.fetch_min(idx, cuda::std::memory_order_relaxed);
#else
        atomic_idx.fetch_max(idx, cuda::std::memory_order_relaxed);
#endif
      });

  print(d_v);

  return 0;
}
```

**Comment by harrism** [comment]
Why is a second reproducer needed @ttnghia ?

**Comment by ttnghia** [comment]
Oh sorry for any confusion. I just want to give more example just in case.
