### ISSUE TITLE
Need docs for `atomic_ref`

### ISSUE THREAD

**Issue by jrhemstad** [NVIDIA/libcudacxx#298]
We have docs for [`cuda::atomic`](https://nvidia.github.io/libcudacxx/extended_api/synchronization_primitives/atomic.html), but none for `cuda::atomic_ref`. 

We should fix that. 

I think this can largely be a copy/paste of the `cuda::atomic` docs as a starting point.

**Comment by wmaxey** [comment]
There are some docs in this PR: #257
