### ISSUE TITLE
[Question] understanding documentation of cuda::atomic::atomic_thread_fence

### ISSUE THREAD

**Issue by nayakajay** [NVIDIA/libcudacxx#308]
I am trying to go through the documentation of thread_fence usage, and I came across this passage [here:](https://nvidia.github.io/libcudacxx/extended_api/synchronization_primitives/atomic/atomic_thread_fence.html#cudaatomicatomic_thread_fence)
```
Establishes memory synchronization ordering of non-atomic and relaxed atomic accesses, as instructed by order, for all threads within scope without an associated atomic operation.
```

My understanding says that atomic operations (via ```atomiCAS``` for example) are relaxed, and non-atomic operations are the general load, store instructions. These are the operations referred in the first half of the passage. The order and scope are well-defined as well. I am having difficulty in understanding the last part which says ```without an associated atomic operation```. Which atomic operation is being referred here? 
A code example for this will be great. Pointers to better understanding will be great too!

Thanks

**Comment by ogiroux** [comment]
You should probably ignore this page and instead just read this other page in these same docs:
https://nvidia.github.io/libcudacxx/extended_api/thread_scopes.html

**Comment by nayakajay** [comment]
Thanks, closing the issue
