### ISSUE TITLE
Linking Clang, llvm-goc, ld, lld against libcu++ for heterogenous execution (gollvm)

### ISSUE THREAD

**Issue by advancedwebdeveloper** [NVIDIA/libcudacxx#37]
Hi.
Not that really saw any working prototype for any C/C++ compiler, which supports accelerating it's workload in a heterogenous manner (I even didn't see that working for GPGPU, yet) - but still curious how much work is required to support this for [gollvm](https://go.googlesource.com/gollvm/) project.
Indeed accelerating [Clang](https://clang.llvm.org/) itself is what shoud be solved first - "llvm-goc" tool, found within gollvm project, itself contains Golang front-end and other stuff, which only trigger Clang's executable (external invocation).
Indeed llvm-goc has some categories of algorithms that are well accelerated by the GPU.

So it leads to an idea of linking Clang (11.0 RC5, as for today) and llvm-goc against your C++ standard library.

Similar approach could be applied against [ld](https://ftp.gnu.org/old-gnu/Manuals/ld-2.9.1/html_mono/ld.html) (less reasonable) and [lld](https://lld.llvm.org/) (more reasonable).
Linker have to finish it's execution, until compiler's session could use the results. But since this is about parallel computing - some compiler-linker pipelines, during build automation, could run in parallel to other compiler-linker workloads.

Please share your thoughts, for a matter of a public discussion.

Ivan

**Comment by brycelelbach** [comment]
Hi Ivan,

I'm not really clear on what you're asking for here, can you clarify? libcu++ is a heterogeneous C++ standard library for CUDA C++ and standard C++. Today, it's primarily supported with the NVCC compiler.

It sounds like you're asking if libcu++ can be used to accelerate the compilation of Go code? That's an really cool idea, but I think it's outside of the scope of this project. You might want to check out our [NVC++ compiler](https://developer.nvidia.com/blog/accelerating-standard-c-with-gpus-using-stdpar/), which transparently accelerates standard C++ parallel algorithms, or [Thrust](https://github.com/NVIDIA/thrust), our parallel algorithms library that inspired the standard C++ parallel algorithms.

**Comment by brycelelbach** [comment]
Closing - please re-open if there's a specific ask for libcu++.
