### ISSUE TITLE
Instead of running all tests for each SM architecture, add specific variants of tests for each SM architecture

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/libcudacxx#38]
This can be accomplished with judicious use of `#include`s of other test sources.

**Comment by griwes** [comment]
I don't understand. Do you want to create a test per SM per every test we have? Why. If that's what this is asking for, that create a massive maintenance burden and incredible code duplication, even with includes. If not, please explain in detail.

**Comment by brycelelbach** [comment]
No. That's exactly the point.

I only want us to create a test for each SM version for each test that actually cares about it.

**Comment by brycelelbach** [comment]
E.g. instead of running all the tests on multiple SM architectures, just run the tests that we need to. Does that make sense?

**Comment by griwes** [comment]
Looking at this now, we definitely need to run all supported tests on every SM we test on.
