### ISSUE TITLE
Add specific tests for ABI version 2

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/libcudacxx#39]
I don't think we test ABI version 2 right now because it's not the default. We should have target tests that force the older ABI version and validate those codepaths. We only need to do this for facilities that have different codepaths in ABI version 3 and ABI version 2.

**Comment by griwes** [comment]
We have those in heterogeneous tests.

**Comment by brycelelbach** [comment]
@griwes we have these tests? So this can be closed?
