### ISSUE TITLE
Copyright in `nv` files

### ISSUE THREAD

**Issue by Beanavil** [NVIDIA/libcudacxx#392]
Files inside the `libcudacxx/include/nv` folder don't have a 
```
// SPDX-FileCopyrightText: Copyright (c) 2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
```
line in the license section. Is that intentional? And, if so, why is that?

**Comment by jrhemstad** [comment]
Thanks for pointing this out! It's definitely not intentional to omit the SPDX copyright line.

This was something on our radar to address a while back, but looks like it fell off the backburner.

**Comment by miscco** [comment]
I have added the copyright notice to all relevant files. Thanks for bringing this up
