### ISSUE TITLE
A device variable cannot be marked constexpr (cuda::std::swap / CTK 11.2)

### ISSUE THREAD

**Issue by senior-zero** [NVIDIA/libcudacxx#409]
There's a compilation error when trying to use libcu++ and CTK 11.2. [Reproducer](https://godbolt.org/z/xhh9Wh1ss):

```cpp
#include <cuda/std/utility>

// cuda/std/detail/libcxx/include/__concepts/../__concepts/../__concepts/swappable.h(173): error: A __device__ variable cannot be marked constexpr
```

**Comment by wmaxey** [comment]
Is this on `main` or 2.1.0? I believe we might have made some adjustments that fix this.

**Comment by senior-zero** [comment]
@wmaxey the issue can be reproduced on main as well as on 2.1.0.
