### ISSUE TITLE
Bump API version from 1.3.1 to 1.4.0

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/libcudacxx#48]
@griwes or @wmaxey can one of you take care of this? We're definitely not going to need a 1.3.1 at this point. The macro is _LIBCUDACXX_CUDA_API_VERSION

**Comment by brycelelbach** [comment]
I lied, I did it. Can someone just review and merge #48?

**Comment by griwes** [comment]
That... References this issue. I'm not seeing an open PR for that commit?

**Comment by brycelelbach** [comment]
I meant #50.
