### ISSUE TITLE
Implement `std::array`

### ISSUE THREAD

**Issue by maddyscientist** [NVIDIA/libcudacxx#51]
Static array storage is commonly used in CUDA programs, and many folks simply resort to reinventing the wheel of `std::array` on the device.  It would be highly desirable to have libcu++ implement `std::array` in the near to medium term to avoid this.

**Comment by mattja** [comment]
As a workaround in the meantime, `std::array` with the experimental nvcc flag `--expt-relaxed-constexpr` works for me.
(interested to know if there are cases where this breaks.)

**Comment by thinelephant** [comment]
@mattja With --expt-relaxed-constexpr, using std::array as const and reading from it is OK. But when using it as non-const, writing to it's elements causes compiling error.

**Comment by kerrmudgeon** [comment]
CUTLASS would definitely appreciate using a `std::array<>` implementation that was part of libcudacxx. 

Like many projects, CUTLASS has implemented its own ["99% compliant"](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/array.h) solution and numerous [partial specializations for arithmetic operators](https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/functional.h) inspired by `<functional>`. 

Converging on a single, interoperable solution seems like it will help developers and offload some of the complexity of CUTLASS.

**Comment by miscco** [comment]
`<cuda/std/array>` is now available so closing this
