### ISSUE TITLE
`cuda::barrier` is default constructible for some reason, while `cuda::std::barrier` is not

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/libcudacxx#83]
https://godbolt.org/z/Ka6GKb

http://eel.is/c++draft/thread.barrier.class

Neither should be default constructible.

**Comment by griwes** [comment]
It's default constructible so that you can put it into shared memory (including the future where there's dynamic init for that - unless you can refer to the block size variables in shared variable construction somehow?).
