### ISSUE TITLE
XFAIL pipeline tests for older CUDA versions

### ISSUE THREAD

**Issue by brycelelbach** [NVIDIA/libcudacxx#99]
When we turn on gpuCI testing, we'll be testing with an older version of CUDA - probably CUDA 11.0. That means pipeline won't be available. We should mark our pipeline tests as XFAIL for older CUDA - we can do this with the `nvcc-X`/`nvcc-X.Y` feature.

**Comment by griwes** [comment]
`<cuda/pipeline>` now lives in this repository; no action needed.
